export const CATEGORY_GAMES = {
    'mmorpg': 'ММОРПГ',
    'shooter': 'Шутер',
    'strategy': 'Стратегия',
    'moba': 'МОБА',
    'racing': 'Гонки',
    'sports': 'Спорт',
    'social': 'Социальная игра',
    'sandbox': 'Песочница',
    'open-world': 'Открытый мир',
    'survival': 'Выживание',
    'pvp': 'ПВП',
    'pve': 'ПВЭ',
    'pixel': 'Пиксельная графика',
    'voxel': 'Воксельная графика',
    'zombie': 'Зомби-игра',
    'turn-based': 'Пошаговая игра',
    'first-person': 'От первого лица',
    'third-person': 'От третьего лица',
    'top-down': 'Вид сверху',
    'tank': 'Танковая игра',
    'space': 'Космическая игра',
    'sailing': 'Игра о парусном спорте',
    'side-scroller': 'Сайдскроллер',
    'superhero': 'Супергеройская игра',
    'permadeath': 'Перманентная смерть',
    'card': 'Карточная игра',
    'battle-royale': 'Королевская битва',
    'mmo': 'ММО',
    'mmofps': 'ММО шутер от первого лица',
    'mmotps': 'ММО шутер от третьего лица',
    '3d': 'Трёхмерная графика',
    '2d': 'Двухмерная графика',
    'anime': 'Аниме',
    'fantasy': 'Фэнтези',
    'sci-fi': 'Научная фантастика',
    'fighting': 'Файтинг',
    'action-rpg': 'Экшен РПГ',
    'action': 'Экшн',
    'military': 'Военная игра',
    'martial-arts': 'Боевые искусства',
    'flight': 'Полёт',
    'low-spec': 'Низкие системные требования',
    'tower-defense': 'Башенная защита',
    'horror': 'Хоррор',
    'mmorts': 'ММО стратегия в реальном времени',
    'action rpg': 'Экшен РПГ',
    'card game': 'Карточная игра',
    'mmoarpg':'ММОАРПГ',
    'action game':'Экшен',
    'battle royale':'Батл Рояль',
    'arpg' : 'АРПГ'
}

export const TAG_GAMES = {
    "mmorpg": false,
    "shooter": false,
    "strategy": false,
    "moba": false,
    "racing": false,
    "sports": false,
    "social": false,
    "sandbox": false,
    "open-world": false,
    "survival": false,
    "pvp": false,
    "pve": false,
    "pixel": false,
    "voxel": false,
    "zombie": false,
    "turn-based": false,
    "first-person": false,
    "third-Person": false,
    "top-down": false,
    "tank": false,
    "space": false,
    "sailing": false,
    "side-scroller": false,
    "superhero": false,
    "permadeath": false,
    "card": false,
    "battle-royale": false,
    "mmo": false,
    "mmofps": false,
    "mmotps": false,
    "3d": false,
    "2d": false,
    "anime": false,
    "fantasy": false,
    "sci-fi": false,
    "fighting": false,
    "action-rpg": false,
    "action": false,
    "military": false,
    "martial-arts": false,
    "flight": false,
    "low-spec": false,
    "tower-defense": false,
    "horror": false,
    "mmorts": false
};